# Generated by Django 5.2.9 on 2025-12-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
